version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: peoples
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./index.sql:/docker-entrypoint-initdb.d/index.sql

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  db_data:
